version: '3.8'

services:
  app:
    build: .
    container_name: nextApp
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://root:prisma@localhost:27017/db?authSource=admin&directConnection=true
      - SECRET=your-secret-key
      - NEXT_PUBLIC_URL=http://localhost:3000
    depends_on:
      - mongodb

  mongodb:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
volumes:
  mongo-data: